Correction requested by csarven
solid/notifications-panel pull request #34
Opened 2021-11-02 19:22 UTC by jaxoncreed

2021-11-03 16:49 UTC, TallTed requested changes

2021-11-03 16:49 UTC, TallTed commented on proposals/solid-webhook-notifications.md
> +The authenticated user during the subscribe request must have READ access to the topic resource. If it does not the server `MUST` reject.
```suggestion
The authenticated user during the subscribe request must have READ access to the topic resource. If it does not, the server `MUST` reject.
```

2021-11-11 16:53 UTC, csarven approved these changes
Thanks for following up on https://github.com/solid/notifications-panel/blob/main/meetings/2021-10-28.md#webhooks-proposal .

Please consider incorporating Ted's suggestions in the PR.

2021-11-16 13:32 UTC, elf-pavlik approved these changes
I think this one can be merged so that we can move the proposal to the other repository.

2021-11-25 15:11 UTC, merged